// DISPLAYING PROJECTS
export const PROJECT_DISPLAY_REQUEST = 'PROJECT_DISPLAY_REQUEST'
export const PROJECT_DISPLAY_SUCCESS = 'PROJECT_DISPLAY_SUCCESS'
export const PROJECT_DISPLAY_FAIL = 'PROJECT_DISPLAY_FAIL' 

// 

