// DISPLAYING PROJECTS
export const PROJECT_DISPLAY_REQUEST = "PROJECT_DISPLAY_REQUEST";
export const PROJECT_DISPLAY_SUCCESS = "PROJECT_DISPLAY_SUCCESS";
export const PROJECT_DISPLAY_FAIL = "PROJECT_DISPLAY_FAIL";

// CREATE NEW PROJECT
export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

// PROJECT DETAIL
export const PROJECT_DETAIL_REQUEST = "PROJECT_DETAIL_REQUEST";
export const PROJECT_DETAIL_SUCCESS = "PROJECT_DETAIL_SUCCESS";
export const PROJECT_DETAIL_FAIL = "PROJECT_DETAIL_FAIL";
export const PROJECT_DETAIL_RESET = "PROJECT_DETAIL_RESET";

// PROJECT_UPDATE
export const PROJECT_UPDATE_REQUEST = "PROJECT_UPDATE_REQUEST";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
export const PROJECT_UPDATE_RESET = "PROJECT_UPDATE_RESET";

// PROJECT USER ROLE
export const PROJECT_USER_ROLE_REQUEST = "PROJECT_USER_ROLE_REQUEST";
export const PROJECT_USER_ROLE_SUCCESS = "PROJECT_USER_ROLE_SUCCESS";
export const PROJECT_USER_ROLE_FAIL = "PROJECT_USER_ROLE_FAIL";
export const PROJECT_USER_ROLE_RESET = "PROJECT_USER_ROLE_RESET";

// DISPLAYING CONTRIBUTORS
export const CONTRIBUTORS_DISPLAY_REQUEST = "CONTRIBUTORS_DISPLAY_REQUEST";
export const CONTRIBUTORS_DISPLAY_SUCCESS = "CONTRIBUTORS_DISPLAY_SUCCESS";
export const CONTRIBUTORS_DISPLAY_FAIL = "CONTRIBUTORS_DISPLAY_FAIL";

// // DELETE CONTRIBUTOR
export const CONTRIBUTOR_DELETE_REQUEST = "CONTRIBUTOR_DELETE_REQUEST";
export const CONTRIBUTOR_DELETE_SUCCESS = "CONTRIBUTOR_DELETE_SUCCESS";
export const CONTRIBUTOR_DELETE_FAIL = "CONTRIBUTOR_DELETE_FAIL";
export const CONTRIBUTOR_DELETE_RESET = "CONTRIBUTOR_DELETE_RESET";

// DISPLAYING ISSUES
export const ISSUES_DISPLAY_REQUEST = "ISSUES_DISPLAY_REQUEST";
export const ISSUES_DISPLAY_SUCCESS = "ISSUES_DISPLAY_SUCCESS";
export const ISSUES_DISPLAY_FAIL = "ISSUES_DISPLAY_FAIL";

// CREATE ISSUES
export const CREATE_ISSUE_REQUEST = "CREATE_ISSUE_REQUEST";
export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS";
export const CREATE_ISSUE_FAIL = "CREATE_ISSUE_FAIL";
export const CREATE_ISSUE_RESET = "CREATE_ISSUE_RESET";

// UPDATE ISSUES
export const UPDATE_ISSUE_REQUEST = "UPDATE_ISSUE_REQUEST";
export const UPDATE_ISSUE_SUCCESS = "UPDATE_ISSUE_SUCCESS";
export const UPDATE_ISSUE_FAIL = "UPDATE_ISSUE_FAIL";
export const UPDATE_ISSUE_RESET = "UPDATE_ISSUE_RESET";

// DELETE ISSUES
export const DELETE_ISSUE_REQUEST = "DELETE_ISSUE_REQUEST";
export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS";
export const DELETE_ISSUE_FAIL = "DELETE_ISSUE_FAIL";
