// DISPLAYING PROJECTS
export const PROJECT_DISPLAY_REQUEST = "PROJECT_DISPLAY_REQUEST";
export const PROJECT_DISPLAY_SUCCESS = "PROJECT_DISPLAY_SUCCESS";
export const PROJECT_DISPLAY_FAIL = "PROJECT_DISPLAY_FAIL";

// CREATE NEW PROJECT
export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

// PROJECT DETAIL
export const PROJECT_DETAIL_REQUEST = "PROJECT_DETAIL_REQUEST";
export const PROJECT_DETAIL_SUCCESS = "PROJECT_DETAIL_SUCCESS";
export const PROJECT_DETAIL_FAIL = "PROJECT_DETAIL_FAIL";
export const PROJECT_DETAIL_RESET = "PROJECT_DETAIL_RESET";

// PROJECT_UPDATE
export const PROJECT_UPDATE_REQUEST = "PROJECT_UPDATE_REQUEST";
export const PROJECT_UPDATE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";
export const PROJECT_UPDATE_RESET = "PROJECT_UPDATE_RESET";
